import "dotenv/config";
import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "../src/generated/prisma/client";
import { hash } from "bcryptjs";

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! });
const prisma = new PrismaClient({ adapter });

type Seeder = (prismaClient: PrismaClient) => Promise<void>;

async function loadLocalSeeder(): Promise<Seeder | null> {
  try {
    const modulePath = "./seed.local";
    const mod = await import(modulePath);
    const maybeSeeder = (mod as { default?: unknown; seed?: unknown }).default ?? (mod as { seed?: unknown }).seed;
    return typeof maybeSeeder === "function" ? (maybeSeeder as Seeder) : null;
  } catch (error: any) {
    const message = String(error?.message ?? "");
    const moduleNotFound =
      error?.code === "ERR_MODULE_NOT_FOUND" ||
      error?.code === "MODULE_NOT_FOUND" ||
      message.includes("Cannot find module") ||
      message.includes("seed.local");
    if (moduleNotFound) return null;
    throw error;
  }
}

async function seedExampleData(prismaClient: PrismaClient) {
  const adminEmail = process.env.SEED_ADMIN_EMAIL ?? "admin@example.com";
  const adminPassword = process.env.SEED_ADMIN_PASSWORD ?? "Admin123!";
  const adminUsername = process.env.SEED_ADMIN_USERNAME ?? "Admin";

  console.log("🌱 Seeding database (example data)...");

  const passwordHash = await hash(adminPassword, 12);

  const admin = await prismaClient.user.upsert({
    where: { email: adminEmail },
    update: {},
    create: {
      email: adminEmail,
      username: adminUsername,
      passwordHash,
      role: "SUPER_ADMIN",
    },
  });

  await prismaClient.siteSettings.upsert({
    where: { id: "default" },
    update: {},
    create: {
      id: "default",
      siteName: "Example Portfolio",
      siteDescription: "An example portfolio seeded with sample data.",
      jobTitle: "Full-Stack Developer",
      heroTitle: "Hi, I'm Example Developer",
      heroSubtitle: "This is sample content generated by the Prisma seed script.",
      aboutContent:
        "Replace this content with your own. You can create `prisma/seed.local.ts` (gitignored) to seed private/real data locally.",
      contactEmail: adminEmail,
      socialLinks: {
        github: "https://github.com/example",
        linkedin: "https://www.linkedin.com/in/example",
      },
      seoKeywords: ["Portfolio", "Full-Stack Developer", "Next.js", "TypeScript"],
      knowsAbout: ["TypeScript", "React", "Next.js", "Node.js", "PostgreSQL", "Prisma"],
      technologySlugs: ["typescript", "react", "nextdotjs", "nodedotjs", "postgresql", "prisma"],
    },
  });

  await Promise.all([
    prismaClient.project.upsert({
      where: { slug: "example-project-1" },
      update: {},
      create: {
        title: "Example Project",
        slug: "example-project-1",
        description: "A sample project seeded by Prisma.",
        technologies: ["Next.js", "TypeScript", "Prisma"],
        featured: true,
        published: true,
        sortOrder: 1,
        authorId: admin.id,
      },
    }),
    prismaClient.project.upsert({
      where: { slug: "example-project-2" },
      update: {},
      create: {
        title: "Another Example Project",
        slug: "example-project-2",
        description: "A second sample project seeded by Prisma.",
        technologies: ["PostgreSQL", "Tailwind CSS"],
        featured: false,
        published: true,
        sortOrder: 2,
        authorId: admin.id,
      },
    }),
  ]);

  console.log("\n🎉 Seeding completed!\n");
  console.log("Admin credentials:");
  console.log(`  Email: ${adminEmail}`);
  console.log(`  Password: ${adminPassword}`);
  console.log("\n⚠️  Change these credentials after first login!");
}

async function main() {
  const localSeeder = await loadLocalSeeder();
  if (localSeeder) {
    console.log("🌱 Seeding database (local seed)...");
    await localSeeder(prisma);
    console.log("\n🎉 Seeding completed (local seed)!\n");
    return;
  }

  await seedExampleData(prisma);
}

main()
  .catch((e) => {
    console.error("❌ Seeding failed:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
